### ISSUE TITLE
Support Privacy Manifest

### ISSUE THREAD

**Issue by benMohamed** [segmentio/Sovran-Swift#11]
while I understand that your SDK is not singled out on Apple's list, my reading of the [new requirements](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api)]" applies to app submissions as a whole, meaning that if CodeScanner does not provide a privacy manifest, the app submission will be rejected.

**Comment by bsneed** [comment]
Sovran doesn't use any "required reason" APIs and shouldn't trigger this.  If that changes please let us know.
